//trebuie populata TODO
var stuf={food:[{name:"bred",foame: 9,energie:0,href:"img/bred.png",type:"food",q:0,max_q:10,recipe:[2,3],value:5},
                {name:"faina",foame: 5,energie:0,href:"img/flower.png",type:"food",q:0,max_q:10,recipe:[1],value:5},
                {name:"sendvici",foame:20,energie:5,href:"img/bred.png",type:"food",q:0,max_q:10,value:5}],
          ingredients:[{name:"mar",foame: 6,energie:2,href:"img/mar.png",type:"food",q:0,max_q:10,recipe:[5,6],value:5},
          {name:"faina",foame: 5,energie:0,href:"img/flower.png",type:"food",q:0,max_q:10,recipe:[1],value:5},
          {name:"carot",foame:5,energie:1,href:"img/carot.png",type:"food",q:0,max_q:10,recipe:[1],value:5},
          {name:"row_pig_mit",foame:4,energie:0,href:"img/row_pig_mit.png",type:"food",q:0,max_q:10,recipe:[1],value:5}],
          wepan:[{name:"Wod sord",dmg:1,href:"img/wepons/wod_sword.png",type:"wepon",value:2},{name:"Iron sord",dmg:3,href:"img/wepons/iron_sword.png",type:"wepon",value:6}],
          armur:[{name:"Cover",def:1,href:"img/armur/hed_armur_1.png",type:"hed-armur",value:2,modi:2},
                 {name:"Lether glovs",def:1,href:"img/armur/l_glovs1.png",type:"glovs-armur",value:2,modi:2},
                 {name:"coif",def:3,href:"img/armur/hed_armur_2.png",type:"hed-armur",value:10,modi:2},
                 {name:"Worn pants",def:3,href:"img/armur/pants1.png",type:"leg-armur",value:10,modi:2},
                 {name:"cloth armur",def:5,href:"img/armur/bodi_armur_2.png",type:"bodi-armur",value:20,modi:2},
                 {name:"Lite boots",def:3,href:"img/armur/boots2.png",type:"fit-armur",value:10,modi:2},
                 {name:"armur",def:3,href:"img/armur/hed_armur_1.png",type:"bodi-armur",value:10,modi:2},
                 {name:"wariar glovs",def:5,href:"img/armur/l_glovs2.png",type:"glovs-armur",value:10,modi:2},
                 {name:"lite armur",def:15,href:"img/armur/bodi_armur_1.png",type:"bodi-armur",value:30,modi:2}],
          julary:[{name:"Old ring",hp:1,href:"img/julary/ring1.png",type:"ring",value:5,modi:2},
                  {name:"Old iron ring",dmg:1,hp:1,href:"img/julary/ring2.png",type:"ring",value:10,modi:2},
                  {name:"Old earring",hp:1,en:1,href:"img/julary/earring1.png",type:"earring",value:15,modi:2},
                  {name:"Old iron earring",dmg:1,en:2,hp:1,href:"img/julary/earring2.png",type:"earring",value:25,modi:2},
                  {name:"Old lether choker",dmg:1,dex:2,hp:1,href:"img/julary/neck1.png",type:"neckles",value:35,modi:2},
                  {name:"Bone neckles",dmg:1,dex:2,hp:1,href:"img/julary/neck2.png",type:"neckles",value:40,modi:2}],
          items:[{ref:"img/2-white25.png",rest: 1}]
};
//numai primi de la s monster sunt facute bine obiectele TODO
var moster={ s_monster:[{name:"bug",dmg:1,def:1,dex:1,hp:3,href:"img/monsters/bug.png",loot:["l1","l1","l1"],lootnr:1,type:"s"},
                        {name:"Bug",dmg:2,def:1,dex:1,hp:6,href:"img/monsters/bug.png",loot:["l1","l1","l1"],lootnr:1,type:"s"},
                        {name:"Spider",dmg:1,def:1,dex:2,hp:10,href:"img/monsters/spider.png",loot:["l1","l1","l1"],lootnr:1,type:"s"},
                        {name:"Scorpion",dmg:2,def:1,dex:2,hp:12,href:"img/monsters/scorpion.png",loot:["l1","l1","l2"],lootnr:1,type:"s"},
                        {name:"snake",dmg:2,def:2,dex:2,hp:15,href:"img/monsters/snake.png",loot:["l1","l1","l2"],lootnr:1,type:"s"},
                        {name:"Dead-Head ",dmg:2,def:3,dex:2,hp:17,href:"img/monsters/ded-head.png", loot:["l1","l1","l2"],lootnr:2,type:"s"},
                        {name:"smal monster7",dmg:3,def:1,dex:1,hp:20,href:"img/monsters/snake.png",loot:["l1","l2","l2"],lootnr:2,type:"s"},
                        {name:"smal monster8",dmg:3,def:1,dex:2,hp:22,href:"img/monsters/snake.png",loot:["l1","l2","l2"],lootnr:2,type:"s"},
                        {name:"smal monster9",dmg:3,def:2,dex:1,hp:24,href:"img/monsters/snake.png",loot:["l1","l2","l2"],lootnr:2,type:"s"},
                        {name:"smal monster10",dmg:3,def:2,dex:2,hp:25,href:"img/monsters/snake.png",loot:["l1","l2","l2"],lootnr:3,type:"s"},
                        {name:"smal monster11",dmg:3,def:3,dex:3,hp:30,href:"img/monsters/snake.png",loot:["l1","l2","l2"],lootnr:3,type:"s"},
                        {name:"smal monster12",dmg:4,def:3,dex:4,hp:33,href:"img/monsters/snake.png",loot:["l2","l2","l2"],lootnr:3,type:"s"},
                        {name:"smal monster13",dmg:5,def:3,dex:2,hp:35,href:"img/monsters/snake.png",loot:["l2","l2","l2"],lootnr:3,type:"s"},
                        {name:"smal monster14",dmg:5,def:2,dex:4,hp:37,href:"img/monsters/snake.png",loot:["l2","l2","l2"],lootnr:2,type:"s"},
                        {name:"smal monster15",dmg:6,def:7,dex:2,hp:40,href:"img/monsters/snake.png",loot:["l2","l2","l3"],lootnr:4,type:"s"}
                      ],
            m_monster:[ {name:"medium monster1",dmg:10,def:10,dex:15,hp:60,href:"img/monsters/bug.png",loot:["l2","l2","l3"],lootnr:3,type:"m"},
                        {name:"medium monster2",dmg:10,def:11,dex:15,hp:65,href:"img/monsters/bug.png",loot:["l2","l3","l3"],lootnr:3,type:"m"},
                        {name:"medium monster4",dmg:15,def:13,dex:14,hp:75,href:"img/monsters/scorpion.png",loot:["l2","l3","l3"],lootnr:3,type:"m"},
                        {name:"medium monster3",dmg:10,def:12,dex:15,hp:70,href:"img/monsters/spider.png",loot:["l2","l3","l3"],lootnr:3,type:"m"},
                        {name:"medium monster5",dmg:15,def:14,dex:13,hp:80,href:"img/monsters/snake.png",loot:["l2","l2","l4"],lootnr:3,type:"m"},
                        {name:"medium monster6",dmg:15,def:15,dex:12,hp:85,href:"img/monsters/ded-head.png",loot:["l2","l3","l4"],lootnr:3,type:"m"},
                        {name:"medium monster7",dmg:20,def:16,dex:11,hp:90,href:"img/monsters/ded-head.png",loot:["l1","l4","l4"],lootnr:3,type:"m"},
                        {name:"medium monster8",dmg:20,def:17,dex:10,hp:95,href:"img/monsters/ded-head.png",loot:["l3","l3","l3"],lootnr:3,type:"m"},
                        {name:"medium monster9",dmg:20,def:18,dex:9,hp:100,href:"img/monsters/ded-head.png",loot:["l3","l3","l3"],lootnr:3,type:"m"},
                        {name:"medium monster10",dmg:25,def:19,dex:8,hp:105,href:"img/monsters/ded-head.png",loot:["l3","l4","l3"],lootnr:3,type:"m"},
                        {name:"medium monster11",dmg:25,def:20,dex:7,hp:110,href:"img/monsters/ded-head.png",loot:["l3","l4","l3"],lootnr:3,type:"m"},
                        {name:"medium monster12",dmg:25,def:21,dex:6,hp:115,href:"img/monsters/ded-head.png",loot:["l3","l4","l3"],lootnr:3,type:"m"},
                        {name:"medium monster13",dmg:25,def:22,dex:5,hp:120,href:"img/monsters/ded-head.png",loot:["l4","l4","l3"],lootnr:3,type:"m"},
                        {name:"medium monster14",dmg:25,def:23,dex:4,hp:125,href:"img/monsters/ded-head.png",loot:["l4","l4","l3"],lootnr:3,type:"m"},
                        {name:"medium monster15",dmg:25,def:24,dex:3,hp:130,href:"img/monsters/ded-head.png",loot:["l4","l4","l4"],lootnr:3,type:"m"}
                                  ],
            l_monster:[ {name:"largi monster1",dmg:50,def:48,dex:20,hp:200,href:"img/monsters/bug.png",loot:["l3","l4","l4"],lootnr:6,type:"l"},
                        {name:"largi monster2",dmg:55,def:47,dex:25,hp:172,href:"img/monsters/bug.png",loot:["l4","l4","l4"],lootnr:6,type:"l"},
                        {name:"largi monster3",dmg:60,def:46,dex:30,hp:173,href:"img/monsters/spider.png",loot:["l4","l4","l5"],lootnr:3,type:"l"},
                        {name:"largi monster4",dmg:65,def:45,dex:20,hp:177,href:"img/monsters/scorpion.png",loot:["l5","l4","l4"],lootnr:6,type:"l"},
                        {name:"largi monster5",dmg:75,def:44,dex:25,hp:171,href:"img/monsters/snake.png",loot:["l5","l5","l4"],lootnr:3,type:"l"},
                        {name:"largi monster6",dmg:85,def:43,dex:20,hp:172,href:"img/monsters/ded-head.png", loot:["l5","l5","l4"],lootnr:3,type:"l"},
                        {name:"largi monster7",dmg:90,def:42,dex:35,hp:174,href:"img/monsters/bug.png",loot:["l5","l5","l5"],lootnr:3,type:"l"},
                        {name:"largi monster8",dmg:100,def:41,dex:20,hp:180,href:"img/monsters/bug.png",loot:["l5","l5","l5"],lootnr:3,type:"l"},
                        {name:"largi monster9",dmg:105,def:40,dex:25,hp:170,href:"img/monsters/bug.png",loot:["l6","l5","l4"],lootnr:3,type:"l"},
                        {name:"largi monster10",dmg:110,def:39,dex:40,hp:170,href:"img/monsters/snake.png",loot:["l6","l5","l4"],lootnr:3,type:"l"},
                        {name:"largi monster11",dmg:115,def:38,dex:20,hp:200,href:"img/monsters/ded-head.png",loot:["l6","l5","l5"],lootnr:4,type:"l"},
                        {name:"largi monster12",dmg:120,def:37,dex:25,hp:177,href:"img/monsters/bug.png",loot:["l6","l5","l5"],lootnr:3,type:"l"},
                        {name:"largi monster13",dmg:125,def:36,dex:45,hp:172,href:"img/monsters/bug.png",loot:["l6","l5","l6"],lootnr:3,type:"l"},
                        {name:"largi monster14",dmg:130,def:35,dex:20,hp:190,href:"img/monsters/bug.png",loot:["l6","l5","l6"],lootnr:3,type:"l"}
                        ],
             B_monster:[{name:"colosus",dmg:180,def:80,dex:60,hp:200,href:"img/monsters/bug.png",loot:["l5","l6","l7"],lootnr:3,type:"b"},
                        {name:"bos2",dmg:190,def:70,dex:60,hp:250,href:"img/monsters/bug.png",loot:["l6","l6","l6"],lootnr:3,type:"b"},
                        {name:"bos3",dmg:200,def:75,dex:51,hp:300,href:"img/monsters/scorpion.png",loot:["l5","l7","l7"],lootnr:3,type:"b"},
                        {name:"bos4",dmg:225,def:65,dex:45,hp:350,href:"img/monsters/spider.png",loot:["l6","l7","l7"],lootnr:3,type:"b"},
                        {name:"Pirate",dmg:250,def:63,dex:45,hp:400,href:"img/monsters/snake.png",loot:["l7","l7","l7"],lootnr:2,type:"b"},
                        {name:"Ival wizard",dmg:300,def:60,dex:40,hp:500,href:"img/monsters/ded-head.png", loot:["l8","l8","l8"],lootnr:2,type:"b"}
                                  ]};
var mat=[[1,1,1,1,1,1,1,1],
         [1,2,1,1,1,1,1,],
         [1,14,2,1,1,1,1,1],
         [1,15,1,1,1,1,1,],
         [1,2,1,1,1,1,1,1],
         [1,1,1,2,1,1,1,],
         [2,1,2,1,1,1,1,1],
         [1,1,2,1,1,1,1,],
         [1,1,1,1,1,1,1,1],
         [1,1,1,1,1,1,1,],
         [1,1,1,1,2,1,1,1],
         [1,1,1,1,1,1,1,],
         [1,1,1,1,1,1,1,1],
         [1,1,1,1,2,1,1,],
         [1,1,2,1,1,1,1,1],
         [1,1,1,2,1,1,1,],
         [1,1,1,1,1,2,1,1]];

//trebuie refacute toate imagineile si corectate in options chestii TODO
var hexagoane=[{type:"grass",    options:{shop:false,cooking:true,nr:3,camp:["fire","bag","temperate"],eat:true,cauta:["loot1","loot2","hunt_lite","vegetables","s_monster","m_monster"],batle_feeld:"" },          speed:1.2,ref:"img/green-terain.png"},
               {type:"desert",   options:{shop:false,cooking:true,nr:3,camp:["fire","bag","Cold"],eat:true,cauta:["loot2","loot3","loot4","loot5","s_monster","m_monster"] ,deforest:["twigs","wod"]},            speed:0.9,ref:"img/orange-terain.png"},
               {type:"jungle",  options:{shop:false,cooking:true,nr:4,camp:["no_fire","bag","temperate"],eat:true,cauta:["twigs","wod","fruits","bunny","medium_treasure","lite_monster"],deforest:["twigs","wod"] },speed:0.7,ref:"img/orange-terain.png"},
               {type:"forest",  options:{shop:false,cooking:true,nr:4,camp:["no_fire","bag","Cold"],eat:true,cauta:["pig","sheep","buny","bunny","lite_treasure","lite_monster"],deforest:["twigs","wod"] },         speed:1,ref:"img/orange-terain.png"},
               {type:"swamp",   options:{shop:false,cooking:true,nr:3,camp:["no_fire","bag","temperate"],eat:true,cauta:["pig","sheep","buny","bunny","lite_treasure","lite_monster"] },                             speed:0.5,ref:"img/orange-terain.png"},
               {type:"mountain",options:{shop:false,cooking:true,nr:4,camp:["fire","bag","temperate"],eat:true,cauta:["pig","sheep","buny","bunny","big_treasure","lite_monster"] ,mine:["","",""]},              speed:0.5,ref:"img/orange-terain.png"},
               {type:"hill",     options:{shop:false,cooking:true,nr:3,camp:["fire","bag","Cold"],eat:true,cauta:["pig","sheep","buny","bunny","lite_treasure","lite_monster"] },                                    speed:0.9,ref:"img/orange-terain.png"},
               {type:"inn",      options:{shop:false,cooking:true,nr:3,camp:["fire","inn","warm"],eat:true,cauta:["pig","sheep","buny","bunny","lite_treasure","lite_monster"] },                                    speed:2,ref:"img/orange-terain.png"},
               {type:"pasture",  options:{shop:false,cooking:true,nr:4,camp:["fire","inn","temperate"],eat:true,cauta:["pig","sheep","buny","bunny","lite_treasure","lite_monster"] , worck:["shepherd","build"]},   speed:2,ref:"img/orange-terain.png"},
               {type:"stables",  options:{shop:false,cooking:true,nr:4,camp:["fire","inn","warm"],eat:true,cauta:["pig","sheep","buny","bunny","lite_treasure","lite_monster"] , worck:["clean","build"] },          speed:2,ref:"img/orange-terain.png"},
               {type:"home",     options:{shop:false,cooking:true,nr:4,camp:["fire","inn","warm"],eat:true,cauta:["pig","sheep","buny","bunny","lite_treasure","lite_monster"] , build:"cest"},                      speed:2,ref:"img/orange-terain.png"},
               {type:"shop",     options:{shop:true,cooking:true,nr:3,camp:["fire","inn","warm"],eat:true,cauta:["pig","sheep","buny","bunny","lite_treasure","lite_monster"], craft:true },                         speed:2,ref:"img/orange-terain.png"},
               {type:"warckshop",options:{shop:true,cooking:true,nr:3,camp:["fire","inn","warm"],eat:true,cauta:["pig","sheep","buny","bunny","lite_treasure","lite_monster"] },                                     speed:2,ref:"img/orange-terain.png"},
               {type:"farm",     options:{shop:true,cooking:true,nr:3,camp:["fire","inn","warm"],eat:true,cauta:["loot2","loot3","loot4","loot5","s_monster","s_monster"] , worck:["clean","build"] },           speed:2,ref:"img/farm-terain.png"},
               {type:"palace",  options:{shop:true,cooking:true,nr:3,camp:["fire","inn","warm"],eat:true,cauta:["loot2","loot3","loot4","loot5","s_monster","s_monster"] },                                   speed:2,ref:"img/castel-terain.png"}
             ];
