//trebuie populata TODO
var stuf={food:[{name:"bred",foame: 9,energie:0,href:"img/bred.png",type:"food",q:0,max_q:10,recipe:[2,3],value:5},
                {name:"faina",foame: 5,energie:0,href:"img/flower.png",type:"food",q:0,max_q:10,recipe:[1],value:5},
                {name:"sendvici",foame:20,energie:5,href:"img/bred.png",type:"food",q:0,max_q:10,value:5}],
          ingredients:[{name:"mar",foame: 6,energie:2,href:"img/mar.png",type:"food",q:0,max_q:10,recipe:[5,6],value:5},
          {name:"faina",foame: 5,energie:0,href:"img/flower.png",type:"food",q:0,max_q:10,recipe:[1],value:5},
          {name:"carot",foame:5,energie:1,href:"img/carot.png",type:"food",q:0,max_q:10,recipe:[1],value:5},
          {name:"row_pig_mit",foame:4,energie:0,href:"img/row_pig_mit.png",type:"food",q:0,max_q:10,recipe:[1],value:5}],
          wepan:[{name:"Wod sord",dmg:1,href:"img/wepons/wod_sword.png",type:"wepon",value:2},{name:"Iron sord",dmg:3,href:"img/wepons/iron_sword.png",type:"wepon",value:6}],
          armur:[{name:"Cover",def:1,href:"img/armur/hed_armur_1.png",type:"hed-armur",value:2,modi:2},
                 {name:"Lether glovs",def:1,href:"img/armur/l_glovs1.png",type:"glovs-armur",value:2,modi:2},
                 {name:"coif",def:3,href:"img/armur/hed_armur_2.png",type:"hed-armur",value:10,modi:2},
                 {name:"Worn pants",def:3,href:"img/armur/pants1.png",type:"leg-armur",value:10,modi:2},
                 {name:"cloth armur",def:5,href:"img/armur/bodi_armur_2.png",type:"bodi-armur",value:20,modi:2},
                 {name:"Lite boots",def:3,href:"img/armur/boots2.png",type:"fit-armur",value:10,modi:2},
                 {name:"armur",def:3,href:"img/armur/hed_armur_1.png",type:"bodi-armur",value:10,modi:2},
                 {name:"wariar glovs",def:5,href:"img/armur/l_glovs2.png",type:"glovs-armur",value:10,modi:2},
                 {name:"lite armur",def:15,href:"img/armur/bodi_armur_1.png",type:"bodi-armur",value:30,modi:2}],
          julary:[{name:"Old ring",hp:1,href:"img/julary/ring1.png",type:"ring",value:5,modi:2},
                  {name:"Old iron ring",dmg:1,hp:1,href:"img/julary/ring2.png",type:"ring",value:10,modi:2},
                  {name:"Old earring",hp:1,en:1,href:"img/julary/earring1.png",type:"earring",value:15,modi:2},
                  {name:"Old iron earring",dmg:1,en:2,hp:1,href:"img/julary/earring2.png",type:"earring",value:25,modi:2},
                  {name:"Old lether choker",dmg:1,dex:2,hp:1,href:"img/julary/neck1.png",type:"neckles",value:35,modi:2},
                  {name:"Bone neckles",dmg:1,dex:2,hp:1,href:"img/julary/neck2.png",type:"neckles",value:40,modi:2}],
          items:[{ref:"img/2-white25.png",rest: 1}]
};
//numai primi de la s monster sunt facute bine obiectele TODO
var moster={ s_monster:[{name:"bug",d1:0,d2:0,d3:0,d4:1,d5:1,d6:2,href:"img/monsters/bug.png",wepan:1,armur:0,escape:100,loot:["l1","l2","l3"],lootnr:1},
                        {name:"Bug",d1:0,d2:0,d3:0,d4:1,d5:1,d6:2,href:"img/monsters/bug.png",wepan:1,armur:0,escape:100,loot:["l1","l2","l3"],lootnr:1},
                        {name:"Spider",d1:0,d2:0,d3:1,d4:1,d5:1,d6:2,href:"img/monsters/spider.png",wepan:1,armur:0,escape:100,loot:["l1","l2","l3"],lootnr:1},
                        {name:"Scorpion",d1:0,d2:0,d3:0,d4:1,d5:2,d6:3,href:"img/monsters/scorpion.png",wepan:1,armur:0,escape:100,loot:["l1","l2","l3"],lootnr:1},
                        {name:"snake",d1:0,d2:0,d3:1,d4:1,d5:2,d6:3,href:"img/monsters/snake.png",wepan:1,armur:0,escape:100,loot:["l1","l2","l3"],lootnr:1},
                        {name:"Dead-Head ",d1:0,d2:0,d3:1,d4:2,d5:2,d6:4,href:"img/monsters/ded-head.png",wepan:1,armur:0,escape:99,loot:["l1","l2","l3"],lootnr:1}
                      ],
            m_monster:[ {name:"bug",d1:0,d2:0,d3:0,d4:1,d5:1,d6:2,href:"img/monsters/bug.png",wepan:1,armur:0,escape:100,loot:["l1","l2","l3"],lootnr:1},
                        {name:"Bug",d1:0,d2:0,d3:0,d4:1,d5:1,d6:2,href:"img/monsters/bug.png",wepan:1,armur:0,escape:100,loot:["l1","l2","l3"],lootnr:1},
                        {name:"Spider",d1:0,d2:0,d3:1,d4:1,d5:1,d6:2,href:"img/monsters/spider.png",wepan:1,armur:0,escape:100,loot:["l1","l2","l3"],lootnr:1},
                        {name:"Scorpion",d1:0,d2:0,d3:0,d4:1,d5:2,d6:3,href:"img/monsters/scorpion.png",wepan:1,armur:0,escape:100,loot:["l1","l2","l3"],lootnr:1},
                        {name:"snake",d1:0,d2:0,d3:1,d4:1,d5:2,d6:3,href:"img/monsters/snake.png",wepan:1,armur:0,escape:100,loot:["l1","l2","l3"],lootnr:1},
                        {name:"Dead-Head ",d1:0,d2:0,d3:1,d4:2,d5:2,d6:4,href:"img/monsters/ded-head.png",wepan:1,armur:0,escape:99,loot:["l1","l2","l3"],lootnr:1}
                      ],
            l_monster:[ {name:"bug",d1:0,d2:0,d3:0,d4:1,d5:1,d6:2,href:"img/monsters/bug.png",wepan:1,armur:0,escape:100,loot:["l1","l2","l3"],lootnr:1},
                        {name:"Bug",d1:0,d2:0,d3:0,d4:1,d5:1,d6:2,href:"img/monsters/bug.png",wepan:1,armur:0,escape:100,loot:["l1","l2","l3"],lootnr:1},
                        {name:"Spider",d1:0,d2:0,d3:1,d4:1,d5:1,d6:2,href:"img/monsters/spider.png",wepan:1,armur:0,escape:100,loot:["l1","l2","l3"],lootnr:1},
                        {name:"Scorpion",d1:0,d2:0,d3:0,d4:1,d5:2,d6:3,href:"img/monsters/scorpion.png",wepan:1,armur:0,escape:100,loot:["l1","l2","l3"],lootnr:1},
                        {name:"snake",d1:0,d2:0,d3:1,d4:1,d5:2,d6:3,href:"img/monsters/snake.png",wepan:1,armur:0,escape:100,loot:["l1","l2","l3"],lootnr:1},
                        {name:"Dead-Head ",d1:0,d2:0,d3:1,d4:2,d5:2,d6:4,href:"img/monsters/ded-head.png",wepan:1,armur:0,escape:99,loot:["l1","l2","l3"],lootnr:1}
                      ],
            B_monster:[ {name:"bug",d1:0,d2:0,d3:0,d4:1,d5:1,d6:2,href:"img/monsters/bug.png",wepan:1,armur:0,escape:100,loot:["l1","l2","l3"],lootnr:1},
                        {name:"Bug",d1:0,d2:0,d3:0,d4:1,d5:1,d6:2,href:"img/monsters/bug.png",wepan:1,armur:0,escape:100,loot:["l1","l2","l3"],lootnr:1}
                      ]};
var mat=[[1,1,1,1,1,1,1,1],
         [1,2,1,1,1,1,1,],
         [1,14,2,1,1,1,1,1],
         [1,15,1,1,1,1,1,],
         [1,2,1,1,1,1,1,1],
         [1,1,1,2,1,1,1,],
         [2,1,2,1,1,1,1,1],
         [1,1,2,1,1,1,1,],
         [1,1,1,1,1,1,1,1],
         [1,1,1,1,1,1,1,],
         [1,1,1,1,2,1,1,1],
         [1,1,1,1,1,1,1,],
         [1,1,1,1,1,1,1,1],
         [1,1,1,1,2,1,1,],
         [1,1,2,1,1,1,1,1],
         [1,1,1,2,1,1,1,],
         [1,1,1,1,1,2,1,1]];

//trebuie refacute toate imagineile si corectate in options chestii TODO
var hexagoane=[{type:"grass",    options:{shop:false,cooking:true,nr:3,camp:["fire","bag","temperate"],eat:true,cauta:["loot1","loot2","hunt_lite","vegetables","s_monster","m_monster"],batle_feeld:"" },          speed:1.2,ref:"img/green-terain.png"},
               {type:"desert",   options:{shop:false,cooking:true,nr:3,camp:["fire","bag","Cold"],eat:true,cauta:["loot2","loot3","loot4","loot5","s_monster","m_monster"] ,deforest:["twigs","wod"]},            speed:0.9,ref:"img/orange-terain.png"},
               {type:"jungle",  options:{shop:false,cooking:true,nr:4,camp:["no_fire","bag","temperate"],eat:true,cauta:["twigs","wod","fruits","bunny","medium_treasure","lite_monster"],deforest:["twigs","wod"] },speed:0.7,ref:"img/orange-terain.png"},
               {type:"forest",  options:{shop:false,cooking:true,nr:4,camp:["no_fire","bag","Cold"],eat:true,cauta:["pig","sheep","buny","bunny","lite_treasure","lite_monster"],deforest:["twigs","wod"] },         speed:1,ref:"img/orange-terain.png"},
               {type:"swamp",   options:{shop:false,cooking:true,nr:3,camp:["no_fire","bag","temperate"],eat:true,cauta:["pig","sheep","buny","bunny","lite_treasure","lite_monster"] },                             speed:0.5,ref:"img/orange-terain.png"},
               {type:"mountain",options:{shop:false,cooking:true,nr:4,camp:["fire","bag","temperate"],eat:true,cauta:["pig","sheep","buny","bunny","big_treasure","lite_monster"] ,mine:["","",""]},              speed:0.5,ref:"img/orange-terain.png"},
               {type:"hill",     options:{shop:false,cooking:true,nr:3,camp:["fire","bag","Cold"],eat:true,cauta:["pig","sheep","buny","bunny","lite_treasure","lite_monster"] },                                    speed:0.9,ref:"img/orange-terain.png"},
               {type:"inn",      options:{shop:false,cooking:true,nr:3,camp:["fire","inn","warm"],eat:true,cauta:["pig","sheep","buny","bunny","lite_treasure","lite_monster"] },                                    speed:2,ref:"img/orange-terain.png"},
               {type:"pasture",  options:{shop:false,cooking:true,nr:4,camp:["fire","inn","temperate"],eat:true,cauta:["pig","sheep","buny","bunny","lite_treasure","lite_monster"] , worck:["shepherd","build"]},   speed:2,ref:"img/orange-terain.png"},
               {type:"stables",  options:{shop:false,cooking:true,nr:4,camp:["fire","inn","warm"],eat:true,cauta:["pig","sheep","buny","bunny","lite_treasure","lite_monster"] , worck:["clean","build"] },          speed:2,ref:"img/orange-terain.png"},
               {type:"home",     options:{shop:false,cooking:true,nr:4,camp:["fire","inn","warm"],eat:true,cauta:["pig","sheep","buny","bunny","lite_treasure","lite_monster"] , build:"cest"},                      speed:2,ref:"img/orange-terain.png"},
               {type:"shop",     options:{shop:true,cooking:true,nr:3,camp:["fire","inn","warm"],eat:true,cauta:["pig","sheep","buny","bunny","lite_treasure","lite_monster"], craft:true },                         speed:2,ref:"img/orange-terain.png"},
               {type:"warckshop",options:{shop:true,cooking:true,nr:3,camp:["fire","inn","warm"],eat:true,cauta:["pig","sheep","buny","bunny","lite_treasure","lite_monster"] },                                     speed:2,ref:"img/orange-terain.png"},
               {type:"farm",     options:{shop:true,cooking:true,nr:3,camp:["fire","inn","warm"],eat:true,cauta:["loot2","loot3","loot4","loot5","s_monster","s_monster"] , worck:["clean","build"] },           speed:2,ref:"img/farm-terain.png"},
               {type:"palace",  options:{shop:true,cooking:true,nr:3,camp:["fire","inn","warm"],eat:true,cauta:["loot2","loot3","loot4","loot5","s_monster","s_monster"] },                                   speed:2,ref:"img/castel-terain.png"}
             ];
